//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.17929
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighLandirect.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HighLandirect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (_A)このソフトウェアについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Address4 {
            get {
                return ResourceManager.GetString("Address4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   市町村名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl+S に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlS {
            get {
                return ResourceManager.GetString("ControlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_c)コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   氏名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustName {
            get {
                return ResourceManager.GetString("CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   顧客番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustNo {
            get {
                return ResourceManager.GetString("CustNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_t)切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_D)データ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataMenu {
            get {
                return ResourceManager.GetString("DataMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_D)削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_E)編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_x)終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファックス番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ふりがな に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Furigana {
            get {
                return ResourceManager.GetString("Furigana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_H)ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   敬称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Keisho {
            get {
                return ResourceManager.GetString("Keisho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラベル印刷する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_p)貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostalCD {
            get {
                return ResourceManager.GetString("PostalCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrefectureCD {
            get {
                return ResourceManager.GetString("PrefectureCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrefectureName {
            get {
                return ResourceManager.GetString("PrefectureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品物 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やりなおし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_r)やりなおし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedoMenu {
            get {
                return ResourceManager.GetString("RedoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地域コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegionCD {
            get {
                return ResourceManager.GetString("RegionCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地域名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_s)保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_a)全て選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAllMenu {
            get {
                return ResourceManager.GetString("SelectAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単価 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tanka {
            get {
                return ResourceManager.GetString("Tanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_u) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndoMenu {
            get {
                return ResourceManager.GetString("UndoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なエラーです。Unknown Application Error
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_Z)ズーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomMenu {
            get {
                return ResourceManager.GetString("ZoomMenu", resourceCulture);
            }
        }
    }
}
