//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM リレーションシップのメタデータ

[assembly: EdmRelationshipAttribute("HighLandirect.Domain", "FK_OrderHistoryReceiveCustID_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HighLandirect.Domains.Customer), "OrderHistory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HighLandirect.Domains.OrderHistory), true)]
[assembly: EdmRelationshipAttribute("HighLandirect.Domain", "FK_OrderHistorySendCustID_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HighLandirect.Domains.Customer), "OrderHistory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HighLandirect.Domains.OrderHistory), true)]
[assembly: EdmRelationshipAttribute("HighLandirect.Domain", "FK_OrderReceiveCustID_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HighLandirect.Domains.Customer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HighLandirect.Domains.Order), true)]
[assembly: EdmRelationshipAttribute("HighLandirect.Domain", "FK_OrderSendCustID_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HighLandirect.Domains.Customer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HighLandirect.Domains.Order), true)]

#endregion

namespace HighLandirect.Domains
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class MyDataEntities : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'MyDataEntities' セクションにある接続文字列を使用して新しい MyDataEntities オブジェクトを初期化します。
        /// </summary>
        public MyDataEntities() : base("name=MyDataEntities", "MyDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい MyDataEntities オブジェクトを初期化します。
        /// </summary>
        public MyDataEntities(string connectionString) : base(connectionString, "MyDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい MyDataEntities オブジェクトを初期化します。
        /// </summary>
        public MyDataEntities(EntityConnection connection) : base(connection, "MyDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<OrderHistory> OrderHistories
        {
            get
            {
                if ((_OrderHistories == null))
                {
                    _OrderHistories = base.CreateObjectSet<OrderHistory>("OrderHistories");
                }
                return _OrderHistories;
            }
        }
        private ObjectSet<OrderHistory> _OrderHistories;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<ReportMemo> ReportMemos
        {
            get
            {
                if ((_ReportMemos == null))
                {
                    _ReportMemos = base.CreateObjectSet<ReportMemo>("ReportMemos");
                }
                return _ReportMemos;
            }
        }
        private ObjectSet<ReportMemo> _ReportMemos;
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Store> Stores
        {
            get
            {
                if ((_Stores == null))
                {
                    _Stores = base.CreateObjectSet<Store>("Stores");
                }
                return _Stores;
            }
        }
        private ObjectSet<Store> _Stores;

        #endregion

        #region AddTo メソッド
    
        /// <summary>
        /// Customers EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// OrderHistories EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToOrderHistories(OrderHistory orderHistory)
        {
            base.AddObject("OrderHistories", orderHistory);
        }
    
        /// <summary>
        /// Products EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Orders EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// ReportMemos EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToReportMemos(ReportMemo reportMemo)
        {
            base.AddObject("ReportMemos", reportMemo);
        }
    
        /// <summary>
        /// Stores EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToStores(Store store)
        {
            base.AddObject("Stores", store);
        }

        #endregion

    }

    #endregion

    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighLandirect.Domain", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Customer オブジェクトを作成します。
        /// </summary>
        /// <param name="custNo">CustNo プロパティの初期値。</param>
        /// <param name="custName">CustName プロパティの初期値。</param>
        public static Customer CreateCustomer(global::System.Int32 custNo, global::System.String custName)
        {
            Customer customer = new Customer();
            customer.CustNo = custNo;
            customer.CustName = custName;
            return customer;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustNo
        {
            get
            {
                return _CustNo;
            }
            set
            {
                if (_CustNo != value)
                {
                    OnCustNoChanging(value);
                    ReportPropertyChanging("CustNo");
                    _CustNo = StructuralObject.SetValidValue(value, "CustNo");
                    ReportPropertyChanged("CustNo");
                    OnCustNoChanged();
                }
            }
        }
        private global::System.Int32 _CustNo;
        partial void OnCustNoChanging(global::System.Int32 value);
        partial void OnCustNoChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Furigana
        {
            get
            {
                return _Furigana;
            }
            set
            {
                OnFuriganaChanging(value);
                ReportPropertyChanging("Furigana");
                _Furigana = StructuralObject.SetValidValue(value, true, "Furigana");
                ReportPropertyChanged("Furigana");
                OnFuriganaChanged();
            }
        }
        private global::System.String _Furigana;
        partial void OnFuriganaChanging(global::System.String value);
        partial void OnFuriganaChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustName
        {
            get
            {
                return _CustName;
            }
            set
            {
                OnCustNameChanging(value);
                ReportPropertyChanging("CustName");
                _CustName = StructuralObject.SetValidValue(value, false, "CustName");
                ReportPropertyChanged("CustName");
                OnCustNameChanged();
            }
        }
        private global::System.String _CustName;
        partial void OnCustNameChanging(global::System.String value);
        partial void OnCustNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keisho
        {
            get
            {
                return _Keisho;
            }
            set
            {
                OnKeishoChanging(value);
                ReportPropertyChanging("Keisho");
                _Keisho = StructuralObject.SetValidValue(value, true, "Keisho");
                ReportPropertyChanged("Keisho");
                OnKeishoChanged();
            }
        }
        private global::System.String _Keisho;
        partial void OnKeishoChanging(global::System.String value);
        partial void OnKeishoChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                OnCityNameChanging(value);
                ReportPropertyChanging("CityName");
                _CityName = StructuralObject.SetValidValue(value, true, "CityName");
                ReportPropertyChanged("CityName");
                OnCityNameChanged();
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCD
        {
            get
            {
                return _PostalCD;
            }
            set
            {
                OnPostalCDChanging(value);
                ReportPropertyChanging("PostalCD");
                _PostalCD = StructuralObject.SetValidValue(value, true, "PostalCD");
                ReportPropertyChanged("PostalCD");
                OnPostalCDChanged();
            }
        }
        private global::System.String _PostalCD;
        partial void OnPostalCDChanging(global::System.String value);
        partial void OnPostalCDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrefectureCD
        {
            get
            {
                return _PrefectureCD;
            }
            set
            {
                OnPrefectureCDChanging(value);
                ReportPropertyChanging("PrefectureCD");
                _PrefectureCD = StructuralObject.SetValidValue(value, true, "PrefectureCD");
                ReportPropertyChanged("PrefectureCD");
                OnPrefectureCDChanged();
            }
        }
        private global::System.String _PrefectureCD;
        partial void OnPrefectureCDChanging(global::System.String value);
        partial void OnPrefectureCDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrefectureName
        {
            get
            {
                return _PrefectureName;
            }
            set
            {
                OnPrefectureNameChanging(value);
                ReportPropertyChanging("PrefectureName");
                _PrefectureName = StructuralObject.SetValidValue(value, true, "PrefectureName");
                ReportPropertyChanged("PrefectureName");
                OnPrefectureNameChanged();
            }
        }
        private global::System.String _PrefectureName;
        partial void OnPrefectureNameChanging(global::System.String value);
        partial void OnPrefectureNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionCD
        {
            get
            {
                return _RegionCD;
            }
            set
            {
                OnRegionCDChanging(value);
                ReportPropertyChanging("RegionCD");
                _RegionCD = StructuralObject.SetValidValue(value, true, "RegionCD");
                ReportPropertyChanged("RegionCD");
                OnRegionCDChanged();
            }
        }
        private global::System.String _RegionCD;
        partial void OnRegionCDChanging(global::System.String value);
        partial void OnRegionCDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionName
        {
            get
            {
                return _RegionName;
            }
            set
            {
                OnRegionNameChanging(value);
                ReportPropertyChanging("RegionName");
                _RegionName = StructuralObject.SetValidValue(value, true, "RegionName");
                ReportPropertyChanged("RegionName");
                OnRegionNameChanged();
            }
        }
        private global::System.String _RegionName;
        partial void OnRegionNameChanging(global::System.String value);
        partial void OnRegionNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true, "Address1");
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true, "Address2");
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address3
        {
            get
            {
                return _Address3;
            }
            set
            {
                OnAddress3Changing(value);
                ReportPropertyChanging("Address3");
                _Address3 = StructuralObject.SetValidValue(value, true, "Address3");
                ReportPropertyChanged("Address3");
                OnAddress3Changed();
            }
        }
        private global::System.String _Address3;
        partial void OnAddress3Changing(global::System.String value);
        partial void OnAddress3Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address4
        {
            get
            {
                return _Address4;
            }
            set
            {
                OnAddress4Changing(value);
                ReportPropertyChanging("Address4");
                _Address4 = StructuralObject.SetValidValue(value, true, "Address4");
                ReportPropertyChanged("Address4");
                OnAddress4Changed();
            }
        }
        private global::System.String _Address4;
        partial void OnAddress4Changing(global::System.String value);
        partial void OnAddress4Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true, "Fax");
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone2
        {
            get
            {
                return _Phone2;
            }
            set
            {
                OnPhone2Changing(value);
                ReportPropertyChanging("Phone2");
                _Phone2 = StructuralObject.SetValidValue(value, true, "Phone2");
                ReportPropertyChanged("Phone2");
                OnPhone2Changed();
            }
        }
        private global::System.String _Phone2;
        partial void OnPhone2Changing(global::System.String value);
        partial void OnPhone2Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MailAddress
        {
            get
            {
                return _MailAddress;
            }
            set
            {
                OnMailAddressChanging(value);
                ReportPropertyChanging("MailAddress");
                _MailAddress = StructuralObject.SetValidValue(value, true, "MailAddress");
                ReportPropertyChanged("MailAddress");
                OnMailAddressChanged();
            }
        }
        private global::System.String _MailAddress;
        partial void OnMailAddressChanging(global::System.String value);
        partial void OnMailAddressChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                OnMemoChanging(value);
                ReportPropertyChanging("Memo");
                _Memo = StructuralObject.SetValidValue(value, true, "Memo");
                ReportPropertyChanged("Memo");
                OnMemoChanged();
            }
        }
        private global::System.String _Memo;
        partial void OnMemoChanging(global::System.String value);
        partial void OnMemoChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, "Label");
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private Nullable<global::System.Boolean> _Label;
        partial void OnLabelChanging(Nullable<global::System.Boolean> value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LatestSend
        {
            get
            {
                return _LatestSend;
            }
            set
            {
                OnLatestSendChanging(value);
                ReportPropertyChanging("LatestSend");
                _LatestSend = StructuralObject.SetValidValue(value, "LatestSend");
                ReportPropertyChanged("LatestSend");
                OnLatestSendChanged();
            }
        }
        private Nullable<global::System.DateTime> _LatestSend;
        partial void OnLatestSendChanging(Nullable<global::System.DateTime> value);
        partial void OnLatestSendChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LatestResceive
        {
            get
            {
                return _LatestResceive;
            }
            set
            {
                OnLatestResceiveChanging(value);
                ReportPropertyChanging("LatestResceive");
                _LatestResceive = StructuralObject.SetValidValue(value, "LatestResceive");
                ReportPropertyChanged("LatestResceive");
                OnLatestResceiveChanged();
            }
        }
        private Nullable<global::System.DateTime> _LatestResceive;
        partial void OnLatestResceiveChanging(Nullable<global::System.DateTime> value);
        partial void OnLatestResceiveChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Delete
        {
            get
            {
                return _Delete;
            }
            set
            {
                OnDeleteChanging(value);
                ReportPropertyChanging("Delete");
                _Delete = StructuralObject.SetValidValue(value, "Delete");
                ReportPropertyChanged("Delete");
                OnDeleteChanged();
            }
        }
        private Nullable<global::System.Boolean> _Delete;
        partial void OnDeleteChanging(Nullable<global::System.Boolean> value);
        partial void OnDeleteChanged();

        #endregion

        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderHistoryReceiveCustID_Customer", "OrderHistory")]
        public EntityCollection<OrderHistory> OrderHistory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderHistory>("HighLandirect.Domain.FK_OrderHistoryReceiveCustID_Customer", "OrderHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderHistory>("HighLandirect.Domain.FK_OrderHistoryReceiveCustID_Customer", "OrderHistory", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderHistorySendCustID_Customer", "OrderHistory")]
        public EntityCollection<OrderHistory> OrderHistory1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderHistory>("HighLandirect.Domain.FK_OrderHistorySendCustID_Customer", "OrderHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderHistory>("HighLandirect.Domain.FK_OrderHistorySendCustID_Customer", "OrderHistory", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderReceiveCustID_Customer", "Order")]
        public EntityCollection<Order> Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("HighLandirect.Domain.FK_OrderReceiveCustID_Customer", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("HighLandirect.Domain.FK_OrderReceiveCustID_Customer", "Order", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderSendCustID_Customer", "Order")]
        public EntityCollection<Order> Order1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("HighLandirect.Domain.FK_OrderSendCustID_Customer", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("HighLandirect.Domain.FK_OrderSendCustID_Customer", "Order", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighLandirect.Domain", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Order オブジェクトを作成します。
        /// </summary>
        /// <param name="orderID">OrderID プロパティの初期値。</param>
        /// <param name="orderDate">OrderDate プロパティの初期値。</param>
        /// <param name="receiveCustID">ReceiveCustID プロパティの初期値。</param>
        /// <param name="sendCustID">SendCustID プロパティの初期値。</param>
        /// <param name="productID">ProductID プロパティの初期値。</param>
        public static Order CreateOrder(global::System.Int64 orderID, global::System.DateTime orderDate, global::System.Int32 receiveCustID, global::System.Int32 sendCustID, global::System.Int32 productID)
        {
            Order order = new Order();
            order.OrderID = orderID;
            order.OrderDate = orderDate;
            order.ReceiveCustID = receiveCustID;
            order.SendCustID = sendCustID;
            order.ProductID = productID;
            return order;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value, "OrderID");
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int64 _OrderID;
        partial void OnOrderIDChanging(global::System.Int64 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value, "OrderDate");
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReceiveCustID
        {
            get
            {
                return _ReceiveCustID;
            }
            set
            {
                OnReceiveCustIDChanging(value);
                ReportPropertyChanging("ReceiveCustID");
                _ReceiveCustID = StructuralObject.SetValidValue(value, "ReceiveCustID");
                ReportPropertyChanged("ReceiveCustID");
                OnReceiveCustIDChanged();
            }
        }
        private global::System.Int32 _ReceiveCustID;
        partial void OnReceiveCustIDChanging(global::System.Int32 value);
        partial void OnReceiveCustIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SendCustID
        {
            get
            {
                return _SendCustID;
            }
            set
            {
                OnSendCustIDChanging(value);
                ReportPropertyChanging("SendCustID");
                _SendCustID = StructuralObject.SetValidValue(value, "SendCustID");
                ReportPropertyChanged("SendCustID");
                OnSendCustIDChanged();
            }
        }
        private global::System.Int32 _SendCustID;
        partial void OnSendCustIDChanging(global::System.Int32 value);
        partial void OnSendCustIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value, "ProductID");
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();

        #endregion

        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderReceiveCustID_Customer", "Customer")]
        public Customer CustomerMasterReceive
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderReceiveCustID_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderReceiveCustID_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerMasterReceiveReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderReceiveCustID_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("HighLandirect.Domain.FK_OrderReceiveCustID_Customer", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderSendCustID_Customer", "Customer")]
        public Customer CustomerMasterSend
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderSendCustID_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderSendCustID_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerMasterSendReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderSendCustID_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("HighLandirect.Domain.FK_OrderSendCustID_Customer", "Customer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighLandirect.Domain", Name="OrderHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderHistory : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい OrderHistory オブジェクトを作成します。
        /// </summary>
        /// <param name="orderID">OrderID プロパティの初期値。</param>
        /// <param name="orderDate">OrderDate プロパティの初期値。</param>
        /// <param name="receiveCustID">ReceiveCustID プロパティの初期値。</param>
        /// <param name="sendCustID">SendCustID プロパティの初期値。</param>
        /// <param name="productID">ProductID プロパティの初期値。</param>
        public static OrderHistory CreateOrderHistory(global::System.Int64 orderID, global::System.DateTime orderDate, global::System.Int32 receiveCustID, global::System.Int32 sendCustID, global::System.Int32 productID)
        {
            OrderHistory orderHistory = new OrderHistory();
            orderHistory.OrderID = orderID;
            orderHistory.OrderDate = orderDate;
            orderHistory.ReceiveCustID = receiveCustID;
            orderHistory.SendCustID = sendCustID;
            orderHistory.ProductID = productID;
            return orderHistory;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value, "OrderID");
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int64 _OrderID;
        partial void OnOrderIDChanging(global::System.Int64 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value, "OrderDate");
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReceiveCustID
        {
            get
            {
                return _ReceiveCustID;
            }
            set
            {
                OnReceiveCustIDChanging(value);
                ReportPropertyChanging("ReceiveCustID");
                _ReceiveCustID = StructuralObject.SetValidValue(value, "ReceiveCustID");
                ReportPropertyChanged("ReceiveCustID");
                OnReceiveCustIDChanged();
            }
        }
        private global::System.Int32 _ReceiveCustID;
        partial void OnReceiveCustIDChanging(global::System.Int32 value);
        partial void OnReceiveCustIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SendCustID
        {
            get
            {
                return _SendCustID;
            }
            set
            {
                OnSendCustIDChanging(value);
                ReportPropertyChanging("SendCustID");
                _SendCustID = StructuralObject.SetValidValue(value, "SendCustID");
                ReportPropertyChanged("SendCustID");
                OnSendCustIDChanged();
            }
        }
        private global::System.Int32 _SendCustID;
        partial void OnSendCustIDChanging(global::System.Int32 value);
        partial void OnSendCustIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value, "ProductID");
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();

        #endregion

        #region ナビゲーション プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderHistoryReceiveCustID_Customer", "Customer")]
        public Customer CustomerMasterReceive
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistoryReceiveCustID_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistoryReceiveCustID_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerMasterReceiveReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistoryReceiveCustID_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistoryReceiveCustID_Customer", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighLandirect.Domain", "FK_OrderHistorySendCustID_Customer", "Customer")]
        public Customer CustomerMasterSend
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistorySendCustID_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistorySendCustID_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerMasterSendReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistorySendCustID_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("HighLandirect.Domain.FK_OrderHistorySendCustID_Customer", "Customer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighLandirect.Domain", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Product オブジェクトを作成します。
        /// </summary>
        /// <param name="productID">ProductID プロパティの初期値。</param>
        /// <param name="productName">ProductName プロパティの初期値。</param>
        /// <param name="tanka">Tanka プロパティの初期値。</param>
        public static Product CreateProduct(global::System.Int32 productID, global::System.String productName, global::System.Decimal tanka)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.ProductName = productName;
            product.Tanka = tanka;
            return product;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value, "ProductID");
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false, "ProductName");
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tanka
        {
            get
            {
                return _Tanka;
            }
            set
            {
                OnTankaChanging(value);
                ReportPropertyChanging("Tanka");
                _Tanka = StructuralObject.SetValidValue(value, "Tanka");
                ReportPropertyChanged("Tanka");
                OnTankaChanged();
            }
        }
        private global::System.Decimal _Tanka;
        partial void OnTankaChanging(global::System.Decimal value);
        partial void OnTankaChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                OnIsDefaultChanging(value);
                ReportPropertyChanging("IsDefault");
                _IsDefault = StructuralObject.SetValidValue(value, "IsDefault");
                ReportPropertyChanged("IsDefault");
                OnIsDefaultChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDefault;
        partial void OnIsDefaultChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDefaultChanged();

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighLandirect.Domain", Name="ReportMemo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReportMemo : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい ReportMemo オブジェクトを作成します。
        /// </summary>
        /// <param name="reportMemoId">ReportMemoId プロパティの初期値。</param>
        public static ReportMemo CreateReportMemo(global::System.Decimal reportMemoId)
        {
            ReportMemo reportMemo = new ReportMemo();
            reportMemo.ReportMemoId = reportMemoId;
            return reportMemo;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReportMemoId
        {
            get
            {
                return _ReportMemoId;
            }
            set
            {
                if (_ReportMemoId != value)
                {
                    OnReportMemoIdChanging(value);
                    ReportPropertyChanging("ReportMemoId");
                    _ReportMemoId = StructuralObject.SetValidValue(value, "ReportMemoId");
                    ReportPropertyChanged("ReportMemoId");
                    OnReportMemoIdChanged();
                }
            }
        }
        private global::System.Decimal _ReportMemoId;
        partial void OnReportMemoIdChanging(global::System.Decimal value);
        partial void OnReportMemoIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReportMemo1
        {
            get
            {
                return _ReportMemo1;
            }
            set
            {
                OnReportMemo1Changing(value);
                ReportPropertyChanging("ReportMemo1");
                _ReportMemo1 = StructuralObject.SetValidValue(value, true, "ReportMemo1");
                ReportPropertyChanged("ReportMemo1");
                OnReportMemo1Changed();
            }
        }
        private global::System.String _ReportMemo1;
        partial void OnReportMemo1Changing(global::System.String value);
        partial void OnReportMemo1Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MemoName
        {
            get
            {
                return _MemoName;
            }
            set
            {
                OnMemoNameChanging(value);
                ReportPropertyChanging("MemoName");
                _MemoName = StructuralObject.SetValidValue(value, true, "MemoName");
                ReportPropertyChanged("MemoName");
                OnMemoNameChanged();
            }
        }
        private global::System.String _MemoName;
        partial void OnMemoNameChanging(global::System.String value);
        partial void OnMemoNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                OnIsDefaultChanging(value);
                ReportPropertyChanging("IsDefault");
                _IsDefault = StructuralObject.SetValidValue(value, "IsDefault");
                ReportPropertyChanged("IsDefault");
                OnIsDefaultChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDefault;
        partial void OnIsDefaultChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDefaultChanged();

        #endregion

    }
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighLandirect.Domain", Name="Store")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Store : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Store オブジェクトを作成します。
        /// </summary>
        /// <param name="id">id プロパティの初期値。</param>
        public static Store CreateStore(global::System.Decimal id)
        {
            Store store = new Store();
            store.id = id;
            return store;
        }

        #endregion

        #region 単純なプロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreId1
        {
            get
            {
                return _StoreId1;
            }
            set
            {
                OnStoreId1Changing(value);
                ReportPropertyChanging("StoreId1");
                _StoreId1 = StructuralObject.SetValidValue(value, true, "StoreId1");
                ReportPropertyChanged("StoreId1");
                OnStoreId1Changed();
            }
        }
        private global::System.String _StoreId1;
        partial void OnStoreId1Changing(global::System.String value);
        partial void OnStoreId1Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreId2
        {
            get
            {
                return _StoreId2;
            }
            set
            {
                OnStoreId2Changing(value);
                ReportPropertyChanging("StoreId2");
                _StoreId2 = StructuralObject.SetValidValue(value, true, "StoreId2");
                ReportPropertyChanged("StoreId2");
                OnStoreId2Changed();
            }
        }
        private global::System.String _StoreId2;
        partial void OnStoreId2Changing(global::System.String value);
        partial void OnStoreId2Changed();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerCD
        {
            get
            {
                return _CustomerCD;
            }
            set
            {
                OnCustomerCDChanging(value);
                ReportPropertyChanging("CustomerCD");
                _CustomerCD = StructuralObject.SetValidValue(value, true, "CustomerCD");
                ReportPropertyChanged("CustomerCD");
                OnCustomerCDChanged();
            }
        }
        private global::System.String _CustomerCD;
        partial void OnCustomerCDChanging(global::System.String value);
        partial void OnCustomerCDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreName
        {
            get
            {
                return _StoreName;
            }
            set
            {
                OnStoreNameChanging(value);
                ReportPropertyChanging("StoreName");
                _StoreName = StructuralObject.SetValidValue(value, true, "StoreName");
                ReportPropertyChanged("StoreName");
                OnStoreNameChanged();
            }
        }
        private global::System.String _StoreName;
        partial void OnStoreNameChanging(global::System.String value);
        partial void OnStoreNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                OnIsDefaultChanging(value);
                ReportPropertyChanging("IsDefault");
                _IsDefault = StructuralObject.SetValidValue(value, "IsDefault");
                ReportPropertyChanged("IsDefault");
                OnIsDefaultChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDefault;
        partial void OnIsDefaultChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDefaultChanged();

        #endregion

    }

    #endregion

}
